# config file for Stop Visits utility

# -------------------------------
# ---- USER INPUT PARAMETERS ----
# -------------------------------

# GTFS File names
#   - Name should include extension (i.e. "good_feed.zip")
#   - IMPORTANT: These feeds need to be in the "data/" directory
#   - Example: 
#
#     gtfs_feeds: 
#       - good_feed.zip
#       - another_good_feed.zip
#

gtfs_feeds:
  - aampo-2019.zip
  - cccxpress-or-us.zip
  - linnshuttle-or-us.zip
  # This feed has multiple issues, including containing csv files and missing 
  # a required field (agency_name in agency.txt)
  # - rvtd-or-us-RIDE.zip
  # Unfortunately trimet is slow enough to require separate testing
  # - trimet.zip
  - albanytransit-or-us.zip
  - josephinecounty-or-us-RIDE.zip
  # LTD will currently fail because it uses calendar_dates for regular service 
  # - ltd-or-us.zip
  - tillamook-or-us.zip