# config file for Average Headways utility

# -------------------------------
# ---- USER INPUT PARAMETERS ----
# -------------------------------

# GTFS File names
#   - Name should include extension (i.e. "good_feed.zip")
#   - IMPORTANT: These feeds need to be in the "data/" directory
#   - Example: 
#
#     gtfs_feeds: 
#       - good_feed.zip
#       - another_good_feed.zip
#

gtfs_feeds:
  # http://oregon-gtfs.com/gtfs_data/benton-or-us/benton-or-us.zip
  - benton-or-us.zip
  # http://oregon-gtfs.com/gtfs_data/canbytransit-or-us/canbytransit-or-us.zip
  - canbytransit-or-us.zip
  # http://oregon-gtfs.com/gtfs_data/tillamook-or-us/tillamook-or-us.zip
  - tillamook-or-us.zip

# Date for which average headways will be calculated
#   - Format: 'YYYYMMDD'
#   - Value should be quoted (single or double)
#   - Example:
#
#     date: '20091102'
#

date: '20201208'

# Time range to average headways over (at this time only one range may be provided)
#   - Format: 'HH:MM:SS'
#   - Value should be quoted (single or double)
#   - Example:
# 
#     time_ranges:
#       - start: '06:00:00'
#         end: '09:00:00'
#

time_ranges:
  - start: '09:00:00'
    end: '17:00:00'