# config file for Cluster Stops utility

# -------------------------------
# ---- USER INPUT PARAMETERS ----
# -------------------------------

# GTFS File names (Required)
#   - Name should include extension (i.e. "good_feed.zip")
#   - IMPORTANT: These feeds need to be in the input directory ("data/" by default)
#   - Example: 
#
#     gtfs_feeds: 
#       - good_feed.zip
#       - another_good_feed.zip
#

gtfs_feeds:
  # http://oregon-gtfs.com/gtfs_data/albanytransit-or-us/albanytransit-or-us.zip
  - albanytransit-or-us.zip
  # http://oregon-gtfs.com/gtfs_data/linnshuttle-or-us/linnshuttle-or-us.zip
  - linnshuttle-or-us.zip

# Date range to run utilty on (Required)
#   - Date format: 'YYYYMMDD'
#   - Values should be quoted (single or double)
#   - Dates are inclusive
#   - For one day, use the same date for start and end
#   - Example:
#
#     date_range: 
#       start: '20201102'
#       end: '20201107'
#

date_range: 
  start: '20201101'
  end: '20201108'

# Time range to run utility on (Optional)
#   - Format: 'HH:MM:SS'
#   - Value should be quoted (single or double)
#   - Range should be defined by 'start' and 'end'
#   - Time range is inclusive
#   - Example:
# 
#     time_range:
#       - start: '06:00:00'
#         end: '09:00:00'
#

time_range:

# Cluster Radius (Required)
#   - Radius (in miles) to cluster stops by
#   - Example:
#
#     cluster_radius: .25
#

cluster_radius: .1