# config file for Stop Visits utility

# -------------------------------
# ---- USER INPUT PARAMETERS ----
# -------------------------------

# GTFS File names
#   - Name should include extension (i.e. "good_feed.zip")
#   - IMPORTANT: These feeds need to be in the "data/" directory
#   - Example: 
#
#     gtfs_feeds: 
#       - good_feed.zip
#       - another_good_feed.zip
#

gtfs_feeds:
