# config file for Interpolate Stoptimes utility

# -------------------------------
# ---- USER INPUT PARAMETERS ----
# -------------------------------

# GTFS File names (Required)
#   - Name should include extension (i.e. "good_feed.zip")
#   - IMPORTANT: These feeds need to be in the input directory ("data/" by default)
#   - Example: 
#
#     gtfs_feeds: 
#       - good_feed.zip
#       - another_good_feed.zip
#

gtfs_feeds:
