# config file for Stop Visits utility

# -------------------------------
# ---- USER INPUT PARAMETERS ----
# -------------------------------

# GTFS File names (Required)
#   - Name should include extension (i.e. "good_feed.zip")
#   - IMPORTANT: These feeds need to be in the input directory ("data/" by default)
#   - Example: 
#
#     gtfs_feeds: 
#       - good_feed.zip
#       - another_good_feed.zip
#

gtfs_feeds:

# Polygon to filter stops on (Optional)
#   - geojson or shapefile 
#   - IMPORTANT: This file (and any accompanying files for .shp files) need to be in the input directory ("data/" by default)
#   - The file must contain only one polygon or multipolygon
#   - Example:
#
#     polygon: polygon.geojson
#

polygon:

# Date range to run utilty on (Required)
#   - Date format: 'YYYYMMDD'
#   - Values should be quoted (single or double)
#   - Dates are inclusive
#   - For one day, use the same date for start and end
#   - Example:
#
#     date_range: 
#       start: '20201102'
#       end: '20201107'
#

date_range:

# Time range to run utility on (Optional)
#   - Format: 'HH:MM:SS'
#   - Value should be quoted (single or double)
#   - Range should be defined by 'start' and 'end'
#   - Time range is inclusive
#   - Example:
# 
#     time_range:
#         start: '06:00:00'
#         end: '09:00:00'
#

time_range:
